version: "3.8"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.0
    container_name: elasticsearch
    user: root
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - sms-network

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.0
    container_name: logstash
    user: root
    depends_on:
      - elasticsearch
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf
    ports:
      - "5959:5959"
    networks:
      - sms-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.0
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    networks:
      - sms-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - sms-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sms-network

  producer:
    image: ddhacks007/sms-simulator-producer:v1
    container_name: producer
    volumes:
      - ./.env:/.env
    depends_on:
      - rabbitmq
      - elasticsearch
      - kibana
      - logstash

    networks:
      - sms-network

  sender:
    image: ddhacks007/sms-simulator-sender:v1
    deploy:
      replicas: 2
    volumes:
      - ./.env:/.env
    depends_on:
      - producer
    networks:
      - sms-network

networks:
  sms-network:
    driver: bridge
